layout_spectrum: 1
color:
  saturation: 0.158423
  lightness: 0.623378
  brandStrength: 1
  brandColors:
    - '#7F7F7F'
    - '#FFFFFF'
    - '#000000'
    - '#A8A8A8'
    - '#F60200'
  rhythmicContrast: 0.575188
typography_spectrum: 0.5998926
name: MotherLoad CrossFit
